services:
    DarkSidePro\SyliusGtmPlugin\EventListener\AddToCartSubscriber:
        arguments:
            - '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\PurchaseSubscriber:
        arguments:
            - '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\CheckoutSubscriber:
        arguments:
            - '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\CartSubscriber:
        arguments:
            - '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\ProductSubscriber:
        arguments:
            - '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\RemoveFromCartSubscriber:
        arguments:
            - '@request_stack'
            - '@DarkSidePro\SyliusGtmPlugin\Factory\EventFactory'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\ViewItemSubscriber:
        arguments:
            - '@request_stack'
            - '@DarkSidePro\SyliusGtmPlugin\Factory\EventFactory'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\ViewItemListSubscriber:
        arguments:
            - '@request_stack'
            - '@DarkSidePro\SyliusGtmPlugin\Factory\EventFactory'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\AddPaymentInfoSubscriber:
        arguments:
            - '@request_stack'
            - '@DarkSidePro\SyliusGtmPlugin\Factory\EventFactory'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\GtmHeadSubscriber:
        arguments:
            - '%env(GTM_CONTAINER_ID)%'
            - '@twig'
        tags:
            - { name: 'kernel.event_subscriber' }
    DarkSidePro\SyliusGtmPlugin\EventListener\GtmBodySubscriber:
        arguments:
            - '%env(GTM_CONTAINER_ID)%'
            - '@twig'
        tags:
            - { name: 'kernel.event_subscriber' }
